/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_nowireless_jni_NativeMethods_Target */

#ifndef _Included_com_github_nowireless_jni_NativeMethods_Target
#define _Included_com_github_nowireless_jni_NativeMethods_Target
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
