/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_nowireless_jni_NativeMethods */

#ifndef _Included_com_github_nowireless_jni_NativeMethods
#define _Included_com_github_nowireless_jni_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    deleteInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_nowireless_jni_NativeMethods_deleteInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    processImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_nowireless_jni_NativeMethods_processImage
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    getHighTargetDistance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_nowireless_jni_NativeMethods_getHighTargetDistance
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    getMiddleTargetDistance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_nowireless_jni_NativeMethods_getMiddleTargetDistance
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    getSecondMiddleDistace
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_nowireless_jni_NativeMethods_getSecondMiddleDistace
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    getHighTargetAzimuth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_nowireless_jni_NativeMethods_getHighTargetAzimuth
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    getMiddleTargetAzimuth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_nowireless_jni_NativeMethods_getMiddleTargetAzimuth
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    getSecondMiddleAzimuth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_github_nowireless_jni_NativeMethods_getSecondMiddleAzimuth
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    isHighTargetVisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_nowireless_jni_NativeMethods_isHighTargetVisable
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    isMiddleTargetVisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_nowireless_jni_NativeMethods_isMiddleTargetVisable
  (JNIEnv *, jclass);

/*
 * Class:     com_github_nowireless_jni_NativeMethods
 * Method:    isSecondMiddleTargetVisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_nowireless_jni_NativeMethods_isSecondMiddleTargetVisable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
